FrontEnd/Models/Popular.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Models
{
    public class Popular
    {
        [Key]
        public string SportName { get; set; }

        public int Total { get; set; }
    }
}

FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Admin()
        {
            return View();
        }
        [Authorize(Roles = "Users")]
        public IActionResult Users()
        {
            return View();
        }

        public IActionResult Popular()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/Controllers/PopularSportController.cs
using FrontEnd.Data;
using FrontEnd.Models;
using FrontEnd.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FrontEnd.Controllers
{
    public class PopularSportController : Controller
    {
        IDataSvc _ds;
        public PopularSportController(IDataSvc ds)
        {
            _ds = ds;

        }

        public ActionResult Popular()
        {



            List<Popular> popularSport = new List<Popular>();

            popularSport = JsonConvert.DeserializeObject<List<Popular>>(_ds.GetSvcPopular());


            return View(popularSport);
        }
    }
}

FrontEnd/Controllers/SportsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Net.Http;
using FrontEnd.Models;
using FrontEnd.Services;

namespace FrontEnd.Controllers
{
    public class SportsController : Controller
    {

        private IDataSvc svcRef;

        public SportsController(IDataSvc dataSvc)
        {
            svcRef = dataSvc;
        }

        // GET: 
        public ActionResult GetSport()
        {
            var webClient = svcRef.GetSvcRef();
            HttpResponseMessage response = webClient.GetAsync(webClient.BaseAddress + "/Sports").Result;

            List<Sport> sList = new List<Sport>();

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                sList = JsonConvert.DeserializeObject<List<Sport>>(data);
            }
            return View(sList);
        }



        // GET: Sport/Create
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sport/Create
        [HttpPost]
        public ActionResult Create(Sport sports)
        {
            string data = JsonConvert.SerializeObject(sports);
            StringContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");

            var webClient = svcRef.GetSvcRef();
            HttpResponseMessage response = webClient.PostAsync(webClient.BaseAddress + "/Sports", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetSport");
            }
            return View();
        }




    }
}

FrontEnd/Views/Home/Admin.cshtml
<style>
    .example_b {
        color: white;
        text-transform: uppercase;
        text-decoration: none;
        /*background: #e1ada8;*/
        opacity: 0.5;
        border-style: solid;
        padding: 40px;
        border-radius: 50px;
        border-bottom: medium;
        display: inline-block;
        transition: all 0.4s ease 0s;
    }

        .example_b:hover {
            text-shadow: 0px 0px 6px rgba(255, 255, 255, 1);
            -webkit-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            -moz-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            transition: all 0.4s ease 0s;
            border-style: solid;
            opacity: 1.0;
        }



    body {
        background-image: url("https://media.istockphoto.com/id/1308693519/photo/football-scene-at-night-match-with-close-up-of-a-soccer-shoe-hitting-the-ball-with-power.jpg?b=1&s=170667a&w=0&k=20&c=VC4hxGaJzeSmae9xb88O7jnCB6oxBLF_VxebIFRjzUU=");
        background-repeat: no-repeat;
        background-position-x: center;
        background-position-y: center;
        background-size: cover;
    }
</style>
<center>
    <h1> Admin Dashboard</h1>
</center>
<br />
<br />
<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Sports/Create" target="_blank" rel="nofollow noopener">Create New Sport</a>
</div>
<br />
<br />

<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Survey/GetSurvey" target="_blank" rel="nofollow noopener">View Sports Rating Report</a>
</div>

@*<h1>Welcome</h1>


    <a asp-controller="Sports" asp-action="Create">Create New Sport</a>
    <br/>
    <br />
    <a asp-controller="Surveys" asp-action="SurveyResult">View Survey Result</a>*@

FrontEnd/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/Site.css" rel="stylesheet" />


<center>
    <br />
    <br />
    <h1 class="chandru"> Sports Survey App</h1>
</center>




<head>

    <style>

        body {
            background-image: url("https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80");
            background-repeat: no-repeat;
            background-position-x: center;
            background-position-y: center;
            background-size: cover;
        }

        .chandru {
            color: blue;
            font-family: cursive;
        }
    </style>


</head>

@*@{
        ViewData["Title"] = "Home Page";
    }

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>*@

FrontEnd/Views/Home/Popular.cshtml
<style>



    body {
        background-color: lightpink;
        background-image: url("https://tse2.mm.bing.net/th/id/OIP.AugOblbBl91_R9R68Bw6twAAAA?pid=ImgDet&w=200&h=200&rs=1");
        background-repeat: no-repeat;
        background-position-x: center;
        background-position-y: center;
        background-size: auto;
    }
</style>
<h4>
    <br />
    <br />
    <center>
        <a asp-controller="PopularSport" asp-action="Popular">View Popular Sport</a>
    </center>
</h4>

FrontEnd/Views/Home/User.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    .example_b {
        color: red;
        text-transform: uppercase;
        text-decoration: none;
        background: #f1a7a7;
        padding: 40px;
        border-radius: 50px;
        border-bottom: medium;
        display: inline-block;
        border: none;
        transition: all 0.4s ease 0s;
    }

        .example_b:hover {
            text-shadow: 0px 0px 6px rgba(255, 255, 255, 1);
            -webkit-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            -moz-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            transition: all 0.4s ease 0s;
        }





    body {
        background-image: url("https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77701686405.jpg");
        background-repeat: no-repeat;
        background-position-x: center;
        background-position-y: top;
        background-size: cover;
    }
</style>
<center>
    <h1>User Dashboard</h1>
</center>
<br />
<br />
<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Sports/GetSport" target="_blank" rel="nofollow noopener">Sports List</a>
</div>
<br />
<br />

<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Survey/RatingSport" target="_blank" rel="nofollow noopener">Click For Sports Rating</a>
</div>

FrontEnd/Views/Home/Users.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    .example_b {
        color: white;
        text-transform: uppercase;
        text-decoration: none;
        /*background: #f1a7a7;*/
        opacity: 0.5;
        border-style: solid;
        padding: 40px;
        border-radius: 50px;
        border-bottom: medium;
        display: inline-block;
        transition: all 0.4s ease 0s;
    }

        .example_b:hover {
            text-shadow: 0px 0px 6px rgba(255, 255, 255, 1);
            -webkit-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            -moz-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
            transition: all 0.4s ease 0s;
            border-style: solid;
            opacity: 1.0;
        }





    body {
        background-image: url("https://media.istockphoto.com/id/1308693519/photo/football-scene-at-night-match-with-close-up-of-a-soccer-shoe-hitting-the-ball-with-power.jpg?b=1&s=170667a&w=0&k=20&c=VC4hxGaJzeSmae9xb88O7jnCB6oxBLF_VxebIFRjzUU=");
        background-repeat: no-repeat;
        background-position-x: center;
        background-position-y: center;
        background-size: cover;
    }
</style>
<center>
    <h1>User Dashboard</h1>
</center>
<br />
<br />
<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Sports/GetSport" target="_blank" rel="nofollow noopener">Sports List</a>
</div>
<br />
<br />

<div class="button_cont" align="center">
    <a class="example_b" href="https://localhost:5001/Survey/RatingSport" target="_blank" rel="nofollow noopener">Click For Sports Rating</a>
</div>